server:
  port: 8090

spring:
  thymeleaf:
    #默认开启Thymeleaf 的缓存，开发环境需要关闭，不然在开发过程中修改页面不会立刻生效需要重启
    cache: false
  #json 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/,classpath:templates
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/autho_sso?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat, wall, logback
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #redis 配置
  redis:
    database: 1
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: 123456
    port: 6379

#mybatis plus 配置
mybatis-plus:
  configuration:
    #数据库字段映射java属性名是否开启自动驼峰命名，默认值为true
    map-underscore-to-camel-case: true
    #当有多个参数时，如果没有@Param注解，默认使用参数名作为别名，否则默认使用索引作为别名
    use-actual-param-name: true
  global-config:
    banner: false
    db-config:
      #全局默认的主键类型，分配ID (主键类型为number或string），默认实现为雪花算法
      id-type: assign_id
      #表名是否使用驼峰转下划线命名,只对表名生效（默认值为true）
      table-underline: true
  type-aliases-package: cn.jackeroo.oauth.entity
  mapper-locations:
    - classpath:com/jackeroo/oauth/dao/mapper/*.xml
